services:
  - type: web
    name: security-scanner-api
    runtime: python
    rootDir: security-scanner
    buildCommand: pip install -r requirements.txt && pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://security-scanner-api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: security-scanner-db
          property: connectionString


databases:
  - name: security-scanner-db
